// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int rounds = Integer.parseInt(args[0]);
		int smaller = 0;
		int bigger = 0;
		for (int i = 0; i<rounds ; i++ ) {
			if (Math.random()>0.5) {
				bigger++;
			}
			else smaller++;
		}
		double ratio = 0.0;
		if (bigger!=0 && smaller!=0) {
			if (bigger>smaller) {
				ratio = (double)smaller / (double)bigger;
			}
			else ratio = (double)bigger / (double)smaller;
			System.out.println("> 0.5:  " + bigger + " times");
			System.out.println("<= 0.5: " + smaller + " times");
			System.out.println("Ratio:  " + ratio);
		} 
	}
}
